- id: nbsexy
  name: nbsexy
  description: "Run nbsexy and specify your check by args."
  entry: nbsexy
  language: python
  types: [jupyter]
- id: nbsexy-cell-count
  name: nbsexy-cell-count
  description: "check number of cell in notebook doesnot exceed provided number, default 20."
  entry: nbsexy --cell_count
  language: python
  types: [jupyter]
- id: nbsexy-is-ascending
  name: nbsexy-is-ascending
  description: "check the cell number(execution_counts) is in ascending order."
  entry: nbsexy --is_ascending
  language: python
  types: [jupyter]
- id: nbsexy-has-md
  name: nbsexy-has-md
  description: "check notebook has at least one markdown cell."
  entry: nbsexy --has_md
  language: python
  types: [jupyter]
- id: nbsexy-line-in-cell
  name: nbsexy-line-in-cell
  description: "check all code cell in notebook have lines less than `max_line_in_cell`."
  entry: nbsexy --line_in_cell
  language: python
  types: [jupyter]
- id: nbsexy-total-line-in-nb
  name: nbsexy-total-line-in-nb
  description: "check sum of lines in all code cells doesnot exceed `max_total_line_in_nb`."
  entry: nbsexy --total_line_in_nb
  language: python
  types: [jupyter]
- id: nbsexy-execute
  name: nbsexy-execute
  description: "Execute your notebook and see if any error raised."
  entry: nbsexy --execute
  language: python
  types: [jupyter]


